language: ruby
os:
  - linux
  - osx
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1"
  - "2.2"
  - jruby-19mode
  - rbx
matrix:
  allow_failures:
  - rvm: jruby-19mode
  - rvm: rbx
  - { rvm: "2.2", os: "osx" } # Ruby 2.2 doesn't seem to be available on OS X on Travis, but works for me locally
